/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ashim
 */
public class SignUp extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
         conn = db.java_db();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        NIC = new javax.swing.JLabel();
        NICText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        professionText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        SignUp = new javax.swing.JButton();
        profession = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setText("Name");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, 40));
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 250, 40));

        NIC.setText("NIC ");
        getContentPane().add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        getContentPane().add(NICText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 250, 40));
        getContentPane().add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 250, 40));
        getContentPane().add(professionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 250, 40));
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 250, 40));

        SignUp.setText("SignUp");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 110, 40));

        profession.setText("Profession");
        getContentPane().add(profession, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        address.setText("Address");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        password.setText("Password");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 632, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:

        if (nameText.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Name is Mandatory");
        } else if (NICText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIC Mandatory");
        } else if (passwordText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password is Mandatory");
        } else {

            try {
                System.out.println(nameText.getText());
                String sql = "insert into signup (Name,NIC, Profession, Password,Address) values (?,?,?,?,?) ";

                pst = conn.prepareStatement(sql);
                pst.setString(1, nameText.getText());
                System.out.println(nameText.getText());
                pst.setString(2, NICText.getText());
                pst.setString(3, professionText.getText());
                pst.setString(4, passwordText.getText());
                pst.setString(5, addressText.getText());

                pst.execute();

                JOptionPane.showMessageDialog(null, "Data is saved successfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error");
            }

            new Login().setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel NIC;
    private javax.swing.JTextField NICText;
    private javax.swing.JLabel Name;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordText;
    private javax.swing.JLabel profession;
    private javax.swing.JTextField professionText;
    // End of variables declaration//GEN-END:variables
}
